title: Bean Validation

profiles:
  development:
  # staging:
  #   base_url: http://test.beanvalidation.org/
  #   deploy:
  #     host: emmanue2@emmanuelbernard.com
  #     path: /home1/emmanue2/public_html/test/beanvalidation
  production:
    base_url: http://beanvalidation.org/
    deploy:
      host: beanvalidation.org
      path: ~/public_html/topdomain-beanvalidation-org

google_analytics: UA-24703879-1