title: Bean Validation

profiles:
  development:
    disqus_developer: true
  production:
    base_url: http://beanvalidation.org/
    deploy:
      host: beanvalidation.org
      path: ~/public_html/topdomain-beanvalidation-org

google_analytics: UA-24703879-1
disqus: beanvalidation